### PR TITLE
feat: support signing key creation and storage in SM

### PR DESCRIPTION
**Pull request by rajatagarwal-ibm**
### Description

support signing key creation and storage in SM

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by brendankellyibm — APPROVED** [review]

**Comment by vburckhardt** [comment]
What is remaining to close on this PR? @rajatagarwal-ibm

**Comment by brendankellyibm** [comment]
We should consider if this PR is necessary now, given that GPG key creation is facilitated in the DevSecOps infrastructure DA - https://github.com/terraform-ibm-modules/terraform-ibm-devsecops-infrastructure/tree/main/gpg-key

If it is valid, you could consider using that module directly.

**Comment by rajatagarwal-ibm** [comment]
Seems key creation is disabled currently, there's no comment so I don't know what might be the reason.
https://github.com/terraform-ibm-modules/terraform-ibm-devsecops-infrastructure/blob/main/gpg-key/gpg.tf
image

**Comment by rajatagarwal-ibm** [comment]
Closing in favour of https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/pull/109

**Pull request closed without merging**
